---
# Fedora-specific tasks
- name: Update system
  package:
    name: "*"
    state: latest

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars
  
- name: Run Linux-specific tasks
  include: "Linux.yml"  