---
# Linux-specific tasks
- name: Add local maintenance user
  user:
    name: "{{ core_ansibleuser_name }}"
#    fullname: "{{ core_ansibleuser_fullname }}"
    comment: "{{ core_ansibleuser_comment }}"
    append: yes
    groups: "{{ core_ansibleuser_admingroup }}"
    password: "{{ core_ansibleuser_password }}"
#    password_never_expires: "{{ core_ansibleuser_password_never_expires }}"
    state: present
    local: yes
#    user_cannot_change_password: yes
    update_password: always
    generate_ssh_key: yes
    ssh_key_type: "{{ core_ansibleuser_sshkey_type }}"
    ssh_key_file: "{{ core_ansibleuser_sshkey_file }}"
    ssh_key_bits: "{{ core_ansibleuser_sshkey_bits }}"
    ssh_key_passphrase: "{{ core_ansibleuser_sshkey_passphrase }}"

- name: Enable passwordless sudo for admin group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ core_ansibleuser_admingroup }}'
    line: '%{{ core_ansibleuser_admingroup }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: core_ansibleuser_passwordless_sudo

- name: Install core packages
  package:
    name: "{{ core.packages }}"
    state: present