---
# Linux-specific tasks
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars
  
- debug:
    msg: "Test: {{ core.ansibleuser.name }}"

- name: Add local maintenance user
  user:
    name: "{{ core.ansibleuser.name }}"
    fullname: "{{ core.ansibleuser.fullname }}"
    comment: "{{ core.ansibleuser.description }}"
    append: yes
    groups: "{{ core.ansibleuser.admingroup }}"
    password: "{{ core.ansibleuser.password }}"
    password_never_expires: "{{ core.ansibleuser.password_never_expires }}"
    state: present
    user_cannot_change_password: yes
    generate_ssh_key: yes
    ssh_key_type: "{{ core.ansibleuser.sshkey.type }}"
    ssh_key_bits: "{{ core.ansibleuser.sshkey.bits }}"
    ssh_key_passphrase: "{{ core.ansibleuser.sshkey.passphrase }}"

- name: Install core packages
  package:
    name: "{{ core.packages }}"
    state: present