---
# Linux-specific tasks
- name: TEST | core from tasks/Linux.yml
  debug:
    msg: "{{ core }}"

- name: Add local maintenance user
  user:
    name: "{{ core.ansibleuser.name }}"
    fullname: "{{ core.ansibleuser.fullname }}"
    comment: "{{ core.ansibleuser.comment }}"
    append: yes
    groups: "{{ core.ansibleuser.admingroup }}"
    password: "{{ core.ansibleuser.password }}"
    password_never_expires: "{{ core.ansibleuser.password_never_expires }}"
    state: present
    user_cannot_change_password: yes
    generate_ssh_key: yes
    ssh_key_type: "{{ core.ansibleuser.sshkey.type }}"
    ssh_key_bits: "{{ core.ansibleuser.sshkey.bits }}"
    ssh_key_passphrase: "{{ core.ansibleuser.sshkey.passphrase }}"

- name: Enable passwordless sudo for admin group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ core.ansibleuser.admingroup }}'
    line: '%{{ core.ansibleuser.admingroup }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    when: core.ansibleuser.passwordless_sudo

- name: Install core packages
  package:
    name: "{{ core.packages }}"
    state: present