---
# Windows-specific tasks
- name: Add local maintenance user
  win_user:
    name: "{{ core.ansibleuser.name }}"
    fullname: "{{ core.ansibleuser.fullname }}"
    description: "{{ core.ansibleuser.description }}"
    groups_action: add
    groups: "{{ core.ansibleuser.admingroup }}"
    password: "{{ core.ansibleuser.password }}"
    password_never_expires: "{{ core.ansibleuser.passwordexpiry }}"
    state: present
    user_cannot_change_password: yes
